package org.jboss.cdi.tck.tests.context.passivating.dependency.resource.webservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-11-11T09:45:02.089+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "HelloWeb", 
                  wsdlLocation = "WEB-INF/HelloWeb.wsdl",
                  targetNamespace = "http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/") 
public class HelloWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/", "HelloWeb");
    public final static QName HelloWebEndpointPort = new QName("http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/", "HelloWebEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("WEB-INF/HelloWeb.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "WEB-INF/HelloWeb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWebService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HelloWeb
     */
    @WebEndpoint(name = "HelloWebEndpointPort")
    public HelloWeb getHelloWebEndpointPort() {
        return super.getPort(HelloWebEndpointPort, HelloWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWeb
     */
    @WebEndpoint(name = "HelloWebEndpointPort")
    public HelloWeb getHelloWebEndpointPort(WebServiceFeature... features) {
        return super.getPort(HelloWebEndpointPort, HelloWeb.class, features);
    }

}
