<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SheepWS" targetNamespace="http://staticProducer.ws.resource.simple.implementation.tests.tck.cdi.jboss.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://staticProducer.ws.resource.simple.implementation.tests.tck.cdi.jboss.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://staticProducer.ws.resource.simple.implementation.tests.tck.cdi.jboss.org/" schemaLocation="SheepWS_schema1.xsd"></import>
</schema>
  </wsdl:types>
  <wsdl:message name="pingResponse">
    <wsdl:part name="parameters" element="tns:pingResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ping">
    <wsdl:part name="parameters" element="tns:ping">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SheepWS">
    <wsdl:operation name="ping">
      <wsdl:input name="ping" message="tns:ping">
    </wsdl:input>
      <wsdl:output name="pingResponse" message="tns:pingResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SheepWSSoapBinding" type="tns:SheepWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ping">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="ping">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="pingResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SheepWS">
    <wsdl:port name="SheepWSEndPointPort" binding="tns:SheepWSSoapBinding">
      <soap:address location="http://localhost:8080/ws-test/SheepWS"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
