= Notes on CDI-lite TCK Updates

This readme file documents the current state of the work to introduce build time support to the TCK. It should be
merged into the TCK guide or a new CDI-lite variation.

The main addition is a `SourceProcessor` interface that has been added to the TCK integration SPI:

[source,java]
----
package org.jboss.cdi.tck.spi;

import java.io.File;
import java.util.Set;

import javax.tools.DiagnosticCollector;
import javax.tools.JavaFileObject;

/**
 * This interface provides operations relating to build time processing of the test archive source.
 *
 * The TCK porting package must provide an implementation of this interface which is suitable for the target implementation.
 *
 */
public interface SourceProcessor {
    public static final String PROPERTY_NAME = SourceProcessor.class.getName();

    /**
     * Called to process the test archive source file. This is called after the base test classes have been added to
     * the test archive. Classes generated in this phase will be added to the test archive to augment or replace
     * existing archive classes.
     *
     * @param testSources - the test source files associated with test archive
     * @param outputDir - the test archive specific directory for any compiler output. Classes found in this directory
     *                  will be added to the test archive to either replace or augment existing classes
     * @param errors - the errors generated during the compliation phase. Any errors will be mapped to CDI deployment
     *               exceptions and propgated to the unit test
     */
    public void process(Set<File> testSources, File outputDir, DiagnosticCollector<JavaFileObject> errors);

}
----

Other additions:

- org.jboss.cdi.tck.shrinkwrap.ArchiveConverter : A utility class that can convert a `WebArchive` into the `JavaArchive`
archive type used by CDI-lite.
- org.jboss.cdi.tck.shrinkwrap.JarArchiveBuilder : A JavaArchive builder extension for CDI-lite deployments. This makes use of the ArchiveBuilder#processSources(Archive) phase.
- ArchiveBuilder#processSources(Archive) phase : Go through paths added by processPackages and processClasses if CDI-lite
is true and there is a {@link SourceProcessor} configured to located the corresponding source files and call the source
processor. This adds any classes generated by the source processor phase to the test archive.
- org.jboss.cdi.tck.test.porting.DummySourceProcessor : Implementation of SourceProcessor that invokes the JavaCompiler to process the test archive source. It also includes a hardcoded reference to the VersionProcessor to validate that annotation processors can run on the test archive.
- org.jboss.cdi.tck.shrinkwrap.WebArchiveBuilder : has been updated to call the ArchiveBuilder#processSources(Archive) phase.

== Two Pass Run Mode for Annotation Processing Based Implementations
The ArchiveBuilder#processSources(Archive) has been updated to place all generated output into a single directory that is specified by the "org.jboss.cdi.tck.sourceProcessorOutputDir" property, which defaults "target/test-classes2". When a SourceProcessor is enabled, the ArchiveBuilder#processSources(Archive) method attaches source to the test archive and then invokes the SourceProcessor#process(...) method to trigger annotation processing and recompilation. This output is placed into the org.jboss.cdi.tck.sourceProcessorOutputDir property setting, or target/test-classes2 if not specified. A maven-surefire-plugin configuration like the following could be used to run two passes of the TCK tests:

[source,xml]
----
        <profile>
            <!-- Run this profile twice to verify the TCK tests against an annotation processor based implementation.
             -->
            <id>twopass-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <excludedGroups>cdi-full,integration,javaee-full,se</excludedGroups>
                            <basedir>${project.basedir}</basedir>
                            <!-- First load from the annotation processor output directory -->
                            <testClassesDirectory>target/test-classes2</testClassesDirectory>
                            <additionalClasspathElements>target/test-classes</additionalClasspathElements>
                            <systemPropertyVariables>
                                <!--arquillian.launch>arc</arquillian.launch-->
                            </systemPropertyVariables>
                            <forkMode>once</forkMode>
                            <suiteXmlFiles>
                                <suiteXmlFile>target/suites/tck-core-tests.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
----
The first pass would run the SourceProcessor for each test archive and produce the augmented classes under target/test-classes2. The second pass would run the tests with archives built from the target/test-classes2 contents.

== Issues

* As part of the TCK setup, the test source archive needs to be extracted to the TCK runner target/suites/src directory in
order for the test source to be located. May need to be configurable.
* Need to identify tests in the core set that relying on any features beyond CDI-lite and add a new TestNG group to filter them out. The issue tracking this is: https://github.com/eclipse-ee4j/cdi-tck/issues/273[CDI-lite test update strategy]
* There is no handling of the JavaCompiler errors passed back from the source processor callout.

