/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,  
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebService(name = "SheepWS", targetNamespace = ObjectFactory.TARGET_NS)
@XmlSeeAlso({ ObjectFactory.class })
public interface SheepWS {

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSheepInjected", targetNamespace = ObjectFactory.TARGET_NS, className = "org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws.IsSheepInjected")
    @ResponseWrapper(localName = "isSheepInjectedResponse", targetNamespace = ObjectFactory.TARGET_NS, className = "org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws.IsSheepInjectedResponse")
    public boolean isSheepInjected();

}
