[[appeals-process]]

== Appeals Process

While the CDI TCK is rigorous about enforcing an implementation's conformance to the Jakarta CDI specification, it's reasonable to assume that an implementor may discover new and/or better ways to validate the assertions.
The appeals process is defined by the Jakarta EE
link:$$https://jakarta.ee/committees/specification/tckprocess/$$[Jakarta EE TCK Process 1.0]


=== What challenges to the TCK may be submitted?

Any test case (e.g., test class, +@Test+ method), test case configuration (e.g., beans.xml), test beans, annotations and other resources may be challenged by an appeal. 

What is generally not challengeable are the assertions made by the specification. The specification document is controlled by a separate process and challenges to it should be handled by the Maintenance Lead or by sending an e-mail to link:$$mailto:cdi-dev@eclipse.org$$

=== How these challenges are submitted?

To submit a challenge, a new issue should be created in the link:$$https://github.com/eclipse-ee4j/cdi$$[CDI specification project] using the label challenge. Any communication regarding the issue should be pursed in the comments of the filed issue for accurate record.

=== How and by whom challenges are addressed?

The challenges will be addressed in a timely fashion by the TCK Lead, as designated by Specification Lead, Red Hat Inc. or his/her designate. The appellant can also monitor the process by following the issue report filed in the link:$$https://github.com/eclipse-ee4j/cdiK$$[CDI TCK project] issues.

The current TCK Lead is listed on the link:$$https://jakarta.ee/specifications/cdi$$[CDI Project Summary Page] on Jakarta EE.

This specification allows for lazy consensus as a resolution path for TCK test challenges as described in the Jakarta EE TCK Process Guide. For this specification, test challenges will be deemed accepted 14 days from the date the test challenge issue is last commented on by a specification team committer, or 14 days from the date of filing if no comments are made by a specification team committer.

If any specification team member determines that the challenge requires review it should be marked with the tag <challenge-review> and it will be resolved under the 'Active Resolution' process as described in the Jakarta EE TCK Process guide. Generally, once a conversation occurs with a member of the committer team, the filer should consider that the challenge will follow the Active Resolution process.

In the event a challenge is approved under lazy consensus, any vendor implementation Compatibility Certification Request (CCR) that uses this challenge must include the issue ID along with the TCK details and test reporting statistics for this specification, regardless if the CCR is filed to this specification project issue tracker, or it is filed for any other specification project issue tracker. Failure to include this issue reference could result in CCR  approval delay.

Once a TCK revision, that includes the resolution of this challenge is released, it is no longer necessary to include any additional reference in your CCR.

=== How accepted challenges to the TCK are managed?
The worflow for TCK challenges is outlined in
link:$$https://jakarta.ee/committees/specification/tckprocess/$$[Jakarta EE TCK Process 1.0].

Periodically, an updated TCK will be released, containing tests altered due to challenges - no new tests will be added. Implementations are required to pass the updated TCK. This release stream is named 5.0.x, where x will be incremented.

Additionally, new tests will be added to the TCK improving coverage of the specification. We encourage implementations to pass this TCK, however it is not required.

