[[sigtest]]

== Running the Signature Test

One of the requirements of an implementation passing the TCK is for it to pass the CDI signature test.
This section describes how to run the signature test against your implementation.

=== Obtaining the sigtest plugin

The sigtest plugin is available from Maven Central using a dependency like:

[source, xml]
----
...
    <plugin>
        <groupId>jakarta.tck</groupId>
        <artifactId>sigtest-maven-plugin</artifactId>
        <version>2.6</version>
    </plugin>
----

The source for the sigtest plugin can be found here: https://github.com/eclipse-ee4j/jakartaee-tck-tools/tree/master/tools/sigtest

=== Running the signature test

To run the signature test, use a POM file like this:

[source, xml]
----
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>2.0.2</version>
    </parent>

    <groupId>jakarta.cdi</groupId>
    <artifactId>cdi-tck-sigtest</artifactId>
    <version>5.0</version>

    <properties>
        <weld.version>7.0.0.Beta1</weld.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jboss.weld</groupId>
            <artifactId>weld-core-impl</artifactId>
            <version>${weld.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>download-sigfile</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>jakarta.cdi</groupId>
                                    <artifactId>jakarta.cdi-tck-core-impl</artifactId>
                                    <version>${version.cdi-tck}</version>
                                    <type>sigfile</type>
                                    <classifier>jdk17</classifier>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                    <destFileName>cdi-api.sigfile</destFileName>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>jakarta.tck</groupId>
                <artifactId>sigtest-maven-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>sigtest</id>
                        <phase>test</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <action>strictcheck</action>
                    <sigfile>${project.build.directory}/cdi-api.sigfile</sigfile>
                    <packages>jakarta.decorator,jakarta.enterprise.**,jakarta.interceptor</packages>
                    <report>${project.build.directory}/cdi-sig-report.xml</report>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

[source]
----
(base) starksm@Scotts-Mac-Studio impl % mvn clean test
...
[INFO] --- sigtest:2.6:check (sigtest) @ cdi-tck-sigtest ---
[INFO] Packages: jakarta.decorator,jakarta.enterprise.**,jakarta.interceptor
Feb 16, 2024 11:42:25 PM com.sun.tdk.signaturetest.SignatureTest parseParameters
INFO: SignatureTest.args: [-FileName, /Users/starksm/Dev/Jakarta/rh-cdi-tck/impl/src/main/resources/cdi-api.sigfile, -static, -ApiVersion, 4.1, -PackageWithoutSubpackages, jakarta.decorator, -Package, jakarta.enterprise, -PackageWithoutSubpackages, jakarta.interceptor, -BootCP, 17, -Classpath, /Users/starksm/Dev/Jakarta/rh-cdi-tck/impl/src/main/resources/target/classes:/Users/starksm/.m2/repository/jakarta/annotation/jakarta.annotation-api/3.0.0-M1/jakarta.annotation-api-3.0.0-M1.jar:/Users/starksm/.m2/repository/jakarta/el/jakarta.el-api/5.0.1/jakarta.el-api-5.0.1.jar:/Users/starksm/.m2/repository/jakarta/interceptor/jakarta.interceptor-api/2.2.0-M1/jakarta.interceptor-api-2.2.0-M1.jar:/Users/starksm/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar:/Users/starksm/.m2/repository/jakarta/enterprise/jakarta.enterprise.lang-model/4.1.0.Beta1/jakarta.enterprise.lang-model-4.1.0.Beta1.jar:/Users/starksm/.m2/repository/jakarta/enterprise/jakarta.enterprise.cdi-api/4.1.0.Beta1/jakarta.enterprise.cdi-api-4.1.0.Beta1.jar]
[INFO] SignatureTest report
Base version: 5.0.0.Beta1
Tested version: 5.0
Check mode: bin [throws removed]
Constant checking: on

Warning: The return type java.lang.reflect.Member can't be resolved
Warning: The return type java.lang.reflect.Member can't be resolved
Warning: The return type java.lang.reflect.Member can't be resolved


[INFO] /Users/starksm/Dev/Jakarta/rh-cdi-tck/impl/src/main/resources/cdi-sig-report.txt: 0 failures in /Users/starksm/Dev/Jakarta/rh-cdi-tck/impl/src/main/resources/cdi-api-jdk17.sigfile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.021 s
[INFO] Finished at: 2024-02-16T23:42:25-06:00
[INFO] ------------------------------------------------------------------------
----

You can ignore the following warnings:

[source]
----
The return type java.lang.reflect.Member can't be resolved
----

The important thing is that Maven shows `BUILD SUCCESS`.

=== CDI Lite signature tests

CDI Lite requires the same signature tests as CDI Full.

If your implementation only supports CDI Lite and does not support CDI Full:

* you are required to provide the exact same CDI API, CDI Lang Model API, and Interceptors API
* you are _not_ required to provide the CDI EL API

To prevent the signature test from failing, you should exclude the relevant package in the `sigtest-maven-plugin` configuration:

[source,xml]
----
<excludes>jakarta.enterprise.inject.spi.el</excludes>
----

=== Forcing a signature test failure

Just for fun (and to confirm that the signature test works correctly), you can try the following:

. Edit `cdi-api.sigfile`

. Modify one of the class signatures.
In the following example, we change one of the constructors of `BusyConversationException`.
Here's the original:
+
[source]
----
CLSS public jakarta.enterprise.context.BusyConversationException
cons public BusyConversationException()
cons public BusyConversationException(java.lang.String)
cons public BusyConversationException(java.lang.String,java.lang.Throwable)
cons public BusyConversationException(java.lang.Throwable)
supr jakarta.enterprise.context.ContextException
hfds serialVersionUID
----
+
Let's change the default (zero-param) constructor to have a `java.lang.Integer` parameter instead:
+
[source]
----
CLSS public jakarta.enterprise.context.BusyConversationException
cons public BusyConversationException(java.lang.Integer)
cons public BusyConversationException(java.lang.String)
cons public BusyConversationException(java.lang.String,java.lang.Throwable)
cons public BusyConversationException(java.lang.Throwable)
supr jakarta.enterprise.context.ContextException
hfds serialVersionUID
----

. Now when we run the signature test, we should get the following errors:
+
[source]
----
Missing Constructors
--------------------

jakarta.enterprise.context.BusyConversationException:       constructor public jakarta.enterprise.context.BusyConversationException.init(java.lang.Integer)

Added Constructors
------------------

jakarta.enterprise.context.BusyConversationException:       constructor public jakarta.enterprise.context.BusyConversationException.init()
----
