<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloWeb" targetNamespace="http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://webservice.resource.dependency.passivating.context.tests.tck.cdi.jboss.org/" schemaLocation="HelloWeb_schema1.xsd"></import>
</schema>
  </wsdl:types>
  <wsdl:message name="sayHello">
    <wsdl:part name="parameters" element="tns:sayHello">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHelloResponse">
    <wsdl:part name="parameters" element="tns:sayHelloResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloWeb">
    <wsdl:operation name="sayHello">
      <wsdl:input name="sayHello" message="tns:sayHello">
    </wsdl:input>
      <wsdl:output name="sayHelloResponse" message="tns:sayHelloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloWebSoapBinding" type="tns:HelloWeb">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHello">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloWeb">
    <wsdl:port name="HelloWebEndpointPort" binding="tns:HelloWebSoapBinding">
      <soap:address location="http://localhost:8080/ws-test/HelloWeb"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
