
package org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SheepWS", targetNamespace = "http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SheepWS {

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSheepInjected", targetNamespace = "http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", className = "org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.IsSheepInjected")
    @ResponseWrapper(localName = "isSheepInjectedResponse", targetNamespace = "http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", className = "org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.IsSheepInjectedResponse")
    public boolean isSheepInjected();

}
