/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SheepWSEndPointService", targetNamespace = "http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", wsdlLocation = "http://localhost:8080/org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.InjectionIntoWebServiceEndPointTest/TestWebService?wsdl")
public class SheepWSEndPointService
    extends Service
{

    private final static URL SHEEPWSENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.SheepWSEndPointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.SheepWSEndPointService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.InjectionIntoWebServiceEndPointTest/TestWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/org.jboss.jsr299.tck.tests.lookup.injection.non.contextual.ws.InjectionIntoWebServiceEndPointTest/TestWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHEEPWSENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public SheepWSEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SheepWSEndPointService() {
        super(SHEEPWSENDPOINTSERVICE_WSDL_LOCATION, new QName("http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", "SheepWSEndPointService"));
    }

    @WebEndpoint(name = "SheepWSPort")
    public SheepWS getSheepWSPort() {
        return super.getPort(new QName("http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", "SheepWSPort"), SheepWS.class);
    }

    @WebEndpoint(name = "SheepWSPort")
    public SheepWS getSheepWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.contextual.non.injection.lookup.tests.tck.jsr299.jboss.org/", "SheepWSPort"), SheepWS.class, features);
    }
}
